#!/bin/dash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

# Use the provided interface, otherwise the device used for the default route.
count=0
[ -n "${BLOCK_INSTANCE}" ] && IF=$BLOCK_INSTANCE || IF=enp4s0

	if [ $count -gt 30 ]; then
	  	IF_NEW=$(ip route | awk '/^default/ { print $5 ; exit }')
	   	count=0
		if [ ! $IF_NEW ="" ]; then
		IF=$IF_NEW
	
		fi
	fi
	count=$((count+1))

	#------------------------------------------------------------------------

	# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
	# connection (think desktop), the corresponding block should not be displayed.

	#------------------------------------------------------------------------
	if [ "$(cat /sys/class/net/${IF}/operstate)" = 'down' ]; then
		echo ""
	else
		case $1 in
		  -4)
		    AF=inet ;;
		  -6)
		    AF=inet6 ;;
		  *)
		    AF=inet6? ;;
		esac

		# if no interface is found, use the first device with a global scope
		IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

		case $BLOCK_BUTTON in
		  3) echo $IPADDR | xclip -selection c && notify-send -u low -a iface "Copied ${IPADDR}" ;;
		esac 

		#------------------------------------------------------------------------

		([ -n "${IPADDR}" ] && echo "<span foreground=\"#f9f9f9\">($IF) $IPADDR</span>") || echo ""
	fi

